language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

cache:
  directories:
    - node_modules

matrix:
  allow_failures:
    - php: 7.0
  fast_finish: true

before_install:
  - if [ "$TRAVIS_PHP_VERSION" == "7.0" ]; then mv phpspec.no-coverage.yml phpspec.yml; fi
  - if [ "$TRAVIS_PHP_VERSION" == "hhvm" ]; then mv phpspec.no-coverage.yml phpspec.yml; fi

install:
  - travis_retry composer install

script:
  - vendor/bin/phpspec run

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - if [ "$TRAVIS_PHP_VERSION" == "5.5" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.xml; fi
  - if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.xml; fi
